/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.product;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@OpenAPIDefinition(info = @Info(title = "APIs", version = "1.7.0", description = "Documentation APIs v1.7.0"))

public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
